
FROM golang:1.22.1-bullseye AS builder

WORKDIR /app


COPY . .


RUN go build -o main ./path/to/your/go/application


FROM ubuntu:latest
WORKDIR /app
COPY --from=builder /app/main .


CMD ["./main"]
